- name: fetch via GIT
  git:
    repo: 'https://github.com/nginx/nginx.git'
    dest: '{{ source_path }}'
    version: '{{ git_version }}'

- name: Install build dependencies
  package:
    name:
      - build-essential
      - libpcre3-dev
      - libssl-dev
      - zlib1g-dev
      - libxslt-dev
      - libgd-dev


- name: Configure
  command: ./auto/configure {{ build_options }}
  args:
    chdir: '{{ source_path }}'


- name: make
  become: yes
  command: make
  args:
    chdir: '{{ source_path }}'


- name: Make install
  command: make install
  args:
    chdir: '{{ source_path }}'


- name: create Systemd file
  copy:
    src: "{{ role_path }}/files/nginx.service"
    dest: /etc/systemd/system/nginx.service


- name: Systemd daemon reload
  command: systemctl daemon-reload


- name: create config directories
  file:
    path: '{{ item.path }}'
    state: directory
  loop:
    - { path: /etc/nginx/conf.d/ }
    - { path: /etc/nginx/sites-enabled/ }
    - { path: /var/lib/nginx }
    - { path: /var/www/html }
  loop_control:
    label: "{{ item.path }}"


- name: copy default webpage
  copy:
    src: "{{ source_path }}/docs/html/index.html"
    dest: /var/www/html/index.html
    remote_src: yes

